### ISSUE TITLE
[Q] njRAT version

### ISSUE THREAD

**Issue by b7001** [NYAN-x-CAT/njRAT-0.7-Stub-For-PowerShell#1]
@NYAN-x-CAT which version of njRAT is used as the server.
Im using njRAT v0.7d at the moment in a VM and the CPU is sitting at around 90% usage (no clients connected)

I will get the md5 soon.

UPDATE:

njRAT v0.7d - 473e1a7be89c3a727176d4f9f5a64b69

**Comment by NYAN-x-CAT** [comment]
You can find a clean version of the server on connect-trojan.
This stub will work on 0.7d and it shouldn't stress the CPU.

**Comment by b7001** [comment]
I downloaded a fresh version from connect-trojan. MD5 is the same as the one i have.

To recreate:
1. Run nj
2. Low to no CPU usage for njRAT SERVER
3. Open stub/client.exe (same results with your C# stub or original vb)
4. Connects back to server
5. SERVER CPU usage around 80-90%, Stub only 1%
6. Disconnect stub/client.exe - server still 80-90% CPU

Any ideas?

**Comment by NYAN-x-CAT** [comment]
No sorry, I don't have any idea.
